export const isoCodes = [
    { name: "Alabama", isoCode: "US-AL" },
    { name: "Alaska", isoCode: "US-AK" },
    { name: "Arizona", isoCode: "US-AZ" },
    { name: "Arkansas", isoCode: "US-AR" },
    { name: "California", isoCode: "US-CA" },
    { name: "Colorado", isoCode: "US-CO" },
    { name: "Connecticut", isoCode: "US-CT" },
    { name: "Delaware", isoCode: "US-DE" },
    { name: "District of Columbia", isoCode: "US-MN" },
    { name: "Florida", isoCode: "US-FL" },
    { name: "Georgia", isoCode: "US-GA" },
    { name: "Hawaii", isoCode: "US-HI" },
    { name: "Idaho", isoCode: "US-ID" },
    { name: "Illinois", isoCode: "US-IL" },
    { name: "Indiana", isoCode: "US-IN" },
    { name: "Iowa", isoCode: "US-IA" },
    { name: "Kansas", isoCode: "US-KS" },
    { name: "Kentucky", isoCode: "US-KY" },
    { name: "Louisiana", isoCode: "US-LA" },
    { name: "Maine", isoCode: "US-ME" },
    { name: "Maryland", isoCode: "US-MD" },
    { name: "Massachusetts", isoCode: "US-MA" },
    { name: "Michigan", isoCode: "US-MI" },
    { name: "Minnesota", isoCode: "US-MN" },
    { name: "Mississippi", isoCode: "US-MS" },
    { name: "Missouri", isoCode: "US-MO" },
    { name: "Montana", isoCode: "US-MT" },
    { name: "Nebraska", isoCode: "US-NE" },
    { name: "Nevada", isoCode: "US-NV" },
    { name: "New Hampshire", isoCode: "US-NH" },
    { name: "New Jersey", isoCode: "US-NJ" },
    { name: "New Mexico", isoCode: "US-NM" },
    { name: "New York", isoCode: "US-NY" },
    { name: "North Carolina", isoCode: "US-NC" },
    { name: "North Dakota", isoCode: "US-ND" },
    { name: "Ohio", isoCode: "US-OH" },
    { name: "Oklahoma", isoCode: "US-OK" },
    { name: "Oregon", isoCode: "US-OR" },
    { name: "Pennsylvania", isoCode: "US-PA" },
    { name: "Puerto Rico", isoCode: "US-RI" },
    { name: "Rhode Island", isoCode: "US-RI" },
    { name: "South Carolina", isoCode: "US-SC" },
    { name: "South Dakota", isoCode: "US-SD" },
    { name: "Tennessee", isoCode: "US-TN" },
    { name: "Texas", isoCode: "US-TX" },
    { name: "Utah", isoCode: "US-UT" },
    { name: "Vermont", isoCode: "US-VT" },
    { name: "Virginia", isoCode: "US-VA" },
    { name: "Washington", isoCode: "US-WA" },
    { name: "West Virginia", isoCode: "US-WV" },
    { name: "Wisconsin", isoCode: "US-WI" },
    { name: "Wyoming", isoCode: "US-WY" }
]